### ISSUE TITLE
Adding  unknown as new severity option

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1190]
### Please describe your feature request:
Currently, the `severity` attribute supports 5 predefined values: `critical,high,medium,low,info` which can be used to include severity information in the template. With the addition of more new templates, we identified cases where any of the available severity values do not fit in any available options.

For the cases where the impact of the issue is not proved/confirmed as a result of the finding and can be decided after further inspection, at the same time using `info` is also not accurate for those templates.

To cover those templates/case, `undefined` severity can be used which is already support at code level but somehow not usable.

```
Invalid severity: undefined
```

### Describe the use case of this feature:

Tagging templates like [token-spray](https://github.com/projectdiscovery/nuclei-templates/search?q=token-spray) with more appropriate severity labels.

----

Suggested by @princechaddha

**Comment by forgedhallpass** [comment]
> To cover those templates/case, undefined severity can be used which is already support at code level but somehow not usable.

`undefined` appears on code level as a side-effect of the `enum` implementation, because `go` does not support such data structures out of the box. It acts as a default value when the severity enum is not properly initalized, but the validation makes sure that such value is not accepted from the users.

If we want to accept such severity value, another "default" value will have to be introduced, taking over the role of the current `undefined`. I am not fan of the idea though, I'd rather "force" the users to look up/calculate the severity of a given vulnerability, otherwise it'd shift the "responsibility" to the end user.
