### ISSUE TITLE
Github rate limit error 

### ISSUE THREAD

**Issue by yashanand** [projectdiscovery/nuclei#126]
![image](https://user-images.githubusercontent.com/21155589/86449141-567a6680-bd35-11ea-8341-16b467b20dbb.png)

**Comment by yashanand** [comment]
Why I am getting this???

**Comment by maverickNerd** [comment]
I am getting this too, I don't think nuclei should check update of templates on each run.

**Comment by devcoinfet** [comment]
Ok my two sense I am getting same error but I decided to handle running all the plugins per yaml by iterating the dir using glob and getting all yamls and than running it like tht we have  a problem either way the plugins get updated  even if before but def not running a scan its rendering your wonderful tool useless basically and i just found it  and wrote python code to use it so please remove the offending code if u could so we can use this wonderful piece of software thank you very much for your help.

**Comment by bauthard** [comment]
Hi @yashanand @devcoinfet, 

This has been fixed in recent release https://github.com/projectdiscovery/nuclei/releases/tag/v2.0.1, as of now nuclei will ignore the error and proceed with the scans instead of stopping the scan. 

@maverickNerd I'm going to create another issue to make the updates optional.
