### ISSUE TITLE
Investigate interactsh integration failing on Github Actions CI

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/nuclei#1287]
### Nuclei version:

Nuclei Dev and Main

### Current Behavior:

Investigate interactsh integration failing on Github Actions CI

**Comment by tanj1m** [comment]
[ERR] Could not initialize interactsh client: could not create client: could not make register request: POST https://interactsh.com/register giving up after 6 attempts: Post "https://interactsh.com/register": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by MMquant** [comment]
It seems like interact.sh have some availability issues. 23-11-2021 it wasn't possible to connect at all and today (24-11-2021) curl connections to https://interact.sh take >20s

**Comment by Mzack9999** [comment]
It seems like those failures happen in the following conditions:

- General container connectivity issues for those integration tests requiring external connectivity
- Issues connecting to port 443 (probably due to failure in certificate renewal - https://github.com/projectdiscovery/interactsh/issues/127)

Review: one possible way to mitigate failure at registration time could be to fall back to http if https fails when contacting the interact endpoint, which should always work if the domain name can be resolved.

**Comment by ehsandeep** [comment]
Follow up ticket created at https://github.com/projectdiscovery/interactsh/issues/144
