### ISSUE TITLE
Supporting DSL helper functions in RAW request

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#131]
> Actually DSL helpers in raw requests are enabled only when payloads are provided (fuzzing), otherwise the request is taken as is (it's made the assumption that if you have to provide only one static value, that can be hardcoded directly). Anyway a good point is raised, as DSL syntax may help as well within normal raw requests without external variables

As of now, DSL helpers in raw requests are enabled only when payloads are provided.

**Comment by dwisiswant0** [comment]
Is this related to this issue?
https://github.com/projectdiscovery/nuclei-templates/issues/172

**Comment by Mzack9999** [comment]
Actually DSL helpers in raw requests are enabled only when payloads are provided (fuzzing), otherwise the request is taken as is (it's made the assumption that if you have to provide only one static value, that can be hardcoded directly). Anyway a good point is raised, as DSL syntax may help as well within normal raw requests without external variables

**Comment by bauthard** [comment]
Done, checkout master @dwisiswant0 to use it.

**Comment by dwisiswant0** [comment]
Kudos to PD team! 🔥
