### ISSUE TITLE
custom vars (custom port) in network template.

### ISSUE THREAD

**Issue by atlassion** [projectdiscovery/nuclei#1330]
Example: 
nuclei -t network/weblogic-t3-detect.yaml -l list -stream -var BPORT=":8004"

"{{Hostname}}{{BPORT}}"

But not working.

**Comment by ehsandeep** [comment]
@atlassion this is because `{{Hostname}}` contains the value for `IP:PORT`, to satisfy your use case, you might want to use `{{Host}}` (not supported in the last release) that holds the value of IP and later you can append the port value using variable or directly in the input list.

`{{Host}}` and `{{Port}}` was not supported previously but are now supported in the development version as part of feature request tracked in - https://github.com/projectdiscovery/nuclei/issues/1205 and will be available to use in next release.
