### ISSUE TITLE
Several consistent false positives

### ISSUE THREAD

**Issue by devcoinfet** [projectdiscovery/nuclei#138]
I know the tool says 0 false positives but that just isn't the case.

CVE-2018-5230
CVE-2019-10475
CVE-2018-20824
CVE-2020-2096
CVE-2019-8449
CVE-2018-1000129
CVE-2019-19368
CVE-2019-12314

these cve's are consistently flagging as being present across several programs that i 100% assure the author they

are not present there are not many false positives and likely better than anything i could do likely but i have to trim these out of my results as they are never correct on these ones and flag too much any suggestions author or can some extra checks be added to verify it's  not some firewall or load balancer  giving us a 200 as there are 100% false positives and im not running my mouth i couldn't make this and i use it so i'm just trying to help.

**Comment by dwisiswant0** [comment]
You can mention the templates author.

**Comment by bauthard** [comment]
Thank you @devcoinfet for creating this issue to make sure tools are consistent, and luckily we already identified at fixed this at https://github.com/projectdiscovery/nuclei-templates/commit/ed4e9e7feb2cb13662b65c7476d366b3c0042b4d, this sudden change was the result of recent PR in nuclei at https://github.com/projectdiscovery/nuclei/pull/125, as such we had to update the template accordingly, so it shouldn’t be an issue if you pull the latest change at https://github.com/projectdiscovery/nuclei-templates, let me know if you see otherwise. 

Again thank you for actively reporting this.

**Comment by devcoinfet** [comment]
thank you and like i said i'm not knocking anyones work i love this tool and has landed me 2 bugs since i started applying it I haven't found a paying but still u get my point i'm impressed I will gladly open issues if i find and ill apply update today.
