### ISSUE TITLE
Add template-id to trace log json

### ISSUE THREAD

**Issue by wgill-tetra** [projectdiscovery/nuclei#2071]
### Please describe your feature request:
Currently the trace log json logs the path to the template but not the id.  Please log the template id in the trace log json.

### Describe the use case of this feature:
Processing trace log output is simpler if the id is in the record.

**Comment by forgedhallpass** [comment]
Could you give a little bit more detail why isn't the template path enough? Currently there is no guarantee (especially in private repositories) that template IDs are unique...

**Comment by wgill-tetra** [comment]
The path to the template could be different between systems but the id is stable.  I expect the id will be unique but good to know that nothing enforces this.  Thanks for your consideration.

**Comment by forgedhallpass** [comment]
The first part of the path could differ, but the section after the nuclei-templates directory should be the same across all installations. We do have validation to warn about duplicate IDs, but I believe the uniqueness is not enforced, because it might not be feasible when private templates also come into play.
