### ISSUE TITLE
Support running all templatess

### ISSUE THREAD

**Issue by mzfr** [projectdiscovery/nuclei#217]
It would be nice if nuclei can support `-t all` or something similar. This is so that all the templates present in the `template directory` are used.

Then to further improve this there can be another option added using which user will be able to exclude a single template directory and run all the remaining one.

Like 
```
nuclei -t all -exclude brute-force
```

This would mean check all the templates except the brute-force one.

**Comment by bauthard** [comment]
Hi @mzfr, 

Excluding template is already done and live in the master, make sure to pull the master if you want to test it, check the PR for details https://github.com/projectdiscovery/nuclei/pull/198

About `all` flag, you can still do this using `-t ~/nuclei-template` but we do not suggest and advise to use in this way, as this is not the expected way to use nuclei, it is focused on more targeted scanning instead of running all at once, for that very specific reason, we choose not to add `all` flag, hope you understand that, closing this for now.

**Comment by cyberblackhole** [comment]
For time being we can make use of the below one

```
mkdir nuclei-all && \
find nuclei-templates/ -name *.yaml -exec cp `basename '{}'` ~/nuclei-all/ \; && \
nuclei -u https://example.com -t ~/nuclei-all
```

**Comment by tanjimXShadow** [comment]
https://indrive.com/

**Comment by tanjimXShadow** [comment]
https://www.techaloy.com/search?search=%3Cscript%3Ealert%28%22hacked+by+annomyous%22%29%3C%2Fscript%3E
