### ISSUE TITLE
convert Catalog to interface for embedded lib use lacking a filesystem

### ISSUE THREAD

**Issue by mikerott** [projectdiscovery/nuclei#2214]
### Please describe your feature request:

It was suggested in [this discussion](https://github.com/projectdiscovery/nuclei/discussions/2183) that `Catalog` be converted to an interface/impl, allowing embedded users to bring their own Catalog implementation.  Related; another suggestion was that "the templates.Parse function accept an io.Reader".

### Describe the use case of this feature:

Since Nuclei embedded use was introduced, my team has used it in AWS lambda, among other places.  We would like the library to support templates-not-from-the-filesystem catalog.  In our case, the templates source is a database, and our usecase is often to bring custom templates written by peer teams for specific product needs.

**Comment by Ice3man543** [comment]
@mikerott I started the conversion to catalog to an interface at https://github.com/projectdiscovery/nuclei/pull/2318/files. However, I'm not sure it'll be of much use for your specific use case unless we change nuclei logic to also read files from catalog. 

Currently, catalog is only used for resolving paths and reading is done in a bunch of places using os.Open and ioutil.ReadFile methods. Instead, we should add a Read method to catalog that should allow us to read from databases/other sources as you mentioned. This is also the reason the PR is still marked in progress since we need to come to a design decision on this. Looking forward to your feedback!

**Comment by Ice3man543** [comment]
@mikerott Added the initial catalog interface implementation and an OpenFile method to the interface as well.

https://github.com/projectdiscovery/nuclei/pull/2318/files#diff-e5e9be2900e2ec6a3356b10e916f4fa3beced2deae8a4266b04d152e8b24927dR6-R21

This seems to satisfy the use case for embedded nuclei usage
