### ISSUE TITLE
Investigate memory usage

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2260]
It has been reported by a user that doing a nuclei scan on a 2GB VPS (kali/debian 11) with default configuration against ~70 hosts would eat up all the memory, hence forcing the OS to kill the process.

TODO:
* [x] add profile generation support to nuclei
* [x] profiling (checking for memory leaks)
* [x] do some benchmarks and note down the resource consumption
* [x] add hardware requirements to the project
* [x] come up with a baseline expectation that can be used for comparison in the future

**Comment by jimen0** [comment]
Hi @forgedhallpass - I profiled nuclei (dev HEAD as of now) running default configuration against 2 hosts for the following templates: `${HOME}/nuclei-templates/exposures/`. Here are some of the results.

`github.com/syndtr/goleveldb/leveldb/memdb.New` -> allocated 12MB (~68% of the total allocations):

<img width="954" alt="image" src="https://user-images.githubusercontent.com/6826244/178476595-86d4557f-754d-46e0-bd6d-133a218b088a.png">

Regular expressions compilation used a lot of memory too (~10% of the total allocations). Given I used a very small number of templates, I'm not sure if this number grows too big when one uses hundreds or thousands of templates. Worth benchmarking the template parsing logic looking for high memory allocations IMHO /cc @ehsandeep 

<img width="954" alt="image" src="https://user-images.githubusercontent.com/6826244/178476975-bfb9cc3d-180f-4454-8a84-45a65e3e495e.png">

and this 2MB in `regexp/syntax.(*compiler).compile`:

<img width="954" alt="image" src="https://user-images.githubusercontent.com/6826244/178477050-3dd11b86-f704-4ebe-bc9c-7fc6ec66ff29.png">

YAML unmarshal logic allocated 2MB too (~1.58% of the total allocs). I see you are using v2 of the module. I'm not sure if v3 improves this, but I believe it might be worth having a look at their changelog. for an easy and quick win? `gopkg.in/yaml%2ev2.(*decoder).unmarshal` results:

<img width="954" alt="image" src="https://user-images.githubusercontent.com/6826244/178477442-ad9959db-3dd1-448d-9e23-085238d62756.png">

In terms of `nuclei`'s code itself, here is the largest allocation path:

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/6826244/178477729-dca4edac-5f51-4d2c-82ff-359b0fd4c438.png">

I think it might be worth profiling the results for a large-scale scan (few hundreds of templates against few thousands of hosts maybe?)

**Comment by jimen0** [comment]
I ran all default templates against a single target (`example.com`). TL;DR: regexp compilation and YAML parsing consume the most memory.

The regexp compilation consumes up to 7MB. 

```code
     74            .     6.49MB           	f := c.compile(re) 
```

The YAML decoder consumes a decent amount of resources too in this case:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/6826244/178481825-bbb45d36-ca9e-476d-b5a6-bd03651deb42.png">
<img width="887" alt="image" src="https://user-images.githubusercontent.com/6826244/178481935-28e89cc1-0f0f-46a9-abbd-40fd809482cf.png">

In terms of nuclei code itself, templates allocation (not parsing, just the allocation!) throws this:

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/6826244/178482132-39d03309-0845-4be5-8eff-505ab3fae2ca.png">

(maybe when using many of these a sync.Pool of them would help? idk since I'm not that used with your codebase)

Execution consumes 11MB.
<img width="883" alt="image" src="https://user-images.githubusercontent.com/6826244/178482292-cf8f5e7d-ccbe-45d1-befc-047e141ae73b.png">

**Comment by Ice3man543** [comment]
Doing some sample runs and capturing data with below list -

- [ ] Executing all templates on a single host
- [ ] Executing all templates on 10 hosts
- [ ] Executing all templates on 100 hosts
- [ ] Executing all templates on 1000 hosts

**Comment by Ice3man543** [comment]
Analysis results after executing several scans - 

| Templates | Target Set | Inuse Memory | Allocated Memory | 
|-----------|------------|---------------|--------------------|
| All             | Single          | 59.22MB         | 3.95GB | 
| All             | 10                 | 95.05MB         | 32.86GB    |
| All             | 100              | 129.10MB         | 342.24GB | 
| All             | 1000            | 194.88MB      | 2.82TB | 

Results after optimizations from #2349 (WIP)


| Templates | Target Set | Inuse Memory | Allocated Memory | 
|-----------|------------|---------------|--------------------|
| All | 10 | 94.95MB | 12.51GB |
