### ISSUE TITLE
panic: sync: WaitGroup is reused before previous Wait has returned

### ISSUE THREAD

**Issue by khalilwtf00** [projectdiscovery/nuclei#3140]
Hello team hope you are good, 
I have an issue where nuclei just stop working with this message 
Killed
![image](https://user-images.githubusercontent.com/24807281/210350403-bdd5d1f3-7107-4d77-beb9-6e8abb334f2c.png)
I tried to locate the location and the source I didn't find anything, 
Keep in mind please that this happen only in the latest version 
Best wishes

**Comment by ehsandeep** [comment]
@khalilwtf00 yesterday we released new version of nuclei that includes a fix for this issue, can you confirm if you were the latest version of nuclei? i.e v2.8.4?

**Comment by khalilwtf00** [comment]
> @khalilwtf00 yesterday we released new version of nuclei that includes a fix for this issue, can you confirm if you were the latest version of nuclei? i.e v2.8.4?

@ehsandeep Thanks for the reply, 
Yes latest version v2.8.4 is used.

**Comment by geeknik** [comment]
I can confirm this behavior is happening with `2.8.4`, but in my case, this only happens when using the `fuzzing-templates`.  My work around is to set `-c 1` to limit the RAM usage.  I am using go1.18.3 on Ubuntu 20.04.5 LTS.

Workflow:
`echo "domain.tld" | subfinder -all | httpx | katana -f qurl | nuclei -t fuzzing-templates -stats`

My list of domains is only 8,621. However, there is a huge spike in RAM usage 2-3 minutes after starting which results in the `Killed` message thanks to the Linux kernel unless the machine has 8+ GB of RAM.

**Comment by khalilwtf00** [comment]
I got this error after 15 mins of working 
![image](https://user-images.githubusercontent.com/24807281/210401200-18543bdf-304e-4a72-9831-e5e1652d2887.png)

**Comment by tarunKoyalwar** [comment]
@khalilwtf00  , this only seems to happen with `host-spray` can you verify if it also happens with `template-spray` strategy and `-c 10` `-bs 200`

**Comment by vzamanillo** [comment]
Regarding the memory issue, I think it's located here

https://github.com/projectdiscovery/nuclei/blob/c273cbc8cb70946fd8065f2dda171afae7bd8189/v2/pkg/protocols/http/request.go#L660-L669

Reading responses / files using `io.Readall`  is not always the best choice because puts all the content into memory, preallocating and reusing buffers with a fixed size (via `sync.poll`) would be a good approach. I am going to open a PR with a proof of concept.

**Comment by khalilwtf00** [comment]
@tarunKoyalwar Thanks for help, 
in the same way I get killed again 
![image](https://user-images.githubusercontent.com/24807281/210663652-46173ef9-7c84-40af-b63a-81c9ef8e2ada.png)

**Comment by marcelo321** [comment]
Same happening to me. When using 1gb linodes. I was doing `ss host-spray -concurrency 150 -bulk-size 10` as per recommended in the wiki, and lowering it more to see if that resolves the issue.

Does lowering concurrency fix the issue? or what can we try? @khalilwtf00

**Comment by khalilwtf00** [comment]
@marcelo321 I tried with 16Gb RAM, with -rl 10 and still crash,

**Comment by tarunKoyalwar** [comment]
@khalilwtf00  , It looks like a memory issue , we are currently in process of fixing this soon for the time being you can also use previous version

**Comment by tarunKoyalwar** [comment]
@khalilwtf00 , @geeknik  the waitgroup issue with `host-spray` should be fixed with attached PR and v2.8.8 .

about memory killed issue we are currently working on something https://github.com/projectdiscovery/nuclei/pull/3203
can you  share if you are facing `killed` issue with below nuclei 
```console 
go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@85b45e8
```
this version of nuclei is linearly scaled so feel free to try it with -c 5000 or even more 

**Note**
`-rl` i.e ratelimit flag limits max concurrency per sec so if we use `-rl 10` then nuclei sends 10 req/s (default is 150 req/s) . so either keep `-rl` default or increase it depending on target

> @marcelo321 I tried with 16Gb RAM, with -rl 10 and still crash,

**Comment by khalilwtf00** [comment]
@tarunKoyalwar Hello,
No killed issue this time with the same target list.

**Comment by tarunKoyalwar** [comment]
@khalilwtf00 
- just to confirm you installed nuclei using below command
```console
go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@85b45e8
```
also how many targets are in target list ??

**Comment by khalilwtf00** [comment]
Yes. 
And the targets list was more than 6500

**Comment by tarunKoyalwar** [comment]
@khalilwtf00  , can you share if you are facing killed issue with attached [PR](https://github.com/projectdiscovery/nuclei/pull/3213) . you can install using
```console
go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@c2a4fd1
```

**Comment by khalilwtf00** [comment]
@tarunKoyalwar Yes, the same targets list, with killed issue after 11 hours of running

**Comment by rxerium** [comment]
Hey team, I'm receiving these wait group errors in v3.2.6. Should I create a new issue?

![image](https://github.com/projectdiscovery/nuclei/assets/59293085/9fdf709b-7488-427c-8ee3-0399daca6432)

**Comment by tarunKoyalwar** [comment]
@rxerium , yes that seems to be a new issue
