### ISSUE TITLE
Add `Connection timed out` error support for `max-host-error` counter

### ISSUE THREAD

**Issue by 0cat-r** [projectdiscovery/nuclei#3165]
The situation is like this, sometimes, security devices such as waf have blocked our server. The phenomenon is that we cannot curl access url

![image](https://user-images.githubusercontent.com/49912303/211153042-839f5130-ba89-4d5e-a9e8-d83882842aa6.png)

I tried using the -mhe parameter to skip the url but it didn't work.

./nuclei  -u  https://xxxx.xxxx.com  -mhe 5 -v -stats
![image](https://user-images.githubusercontent.com/49912303/211152919-ec917450-ded4-4957-9ef1-5a69f4073773.png)
When there are a lot of requests in my xxx.yaml. And when there are many target urls in target.txt. Suppose the first url can't be skipped correctly. The program will be stuck here, unless all requests are timeout

I am using the latest version v2.8.6

**Comment by jaikishantulswani** [comment]
@ehsandeep Can it be possible to skip using `mhe` flag as it uses the flag by default for 30 errors before skipping. What if I want to force scan that domain.

**Comment by ehsandeep** [comment]
@jaikishantulswani, it will be possible after https://github.com/projectdiscovery/nuclei/issues is implemented.

**Comment by 0cat-r** [comment]
@ehsandeep why mhe parameter doesn't work

**Comment by ehsandeep** [comment]
@0cat-r it's because `Connection timed out` error is not used `max-host-error` counter -

https://github.com/projectdiscovery/nuclei/blob/main/v2/pkg/protocols/common/hosterrorscache/hosterrorscache.go#L129

**Comment by Mzack9999** [comment]
A similar error (`Timeout exceeded while awaiting headers` - a bit different as the network connection is established, but no response header received) is counted as a hard fail worth +1 in the host error cache. `Connection Timeout` is quite a risky error to add as it might result from WAF or intentional (e.g. SQL time injection). Maybe we should start assigning a weight to errors rather than a unitary increment, and if the sum is above a certain threshold, then the host is ignored (in this way, a Timeout error would trigger a lower increase than a no IPS found)

**Comment by Mzack9999** [comment]
This will be implemented in https://github.com/projectdiscovery/utils/issues/69 and improved in nuclei auto-tuning - Closing for now
