### ISSUE TITLE
Update Fail

### ISSUE THREAD

**Issue by manojdeshmukh45** [projectdiscovery/nuclei#3255]
While Im trying to update nuclei using "sudo ./nuclei -update", its giving me an error 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.3

                projectdiscovery.io

[================================================] 100%
[FTL] Could not create runner: could not install latest release: looking up path of "nuclei": exec: "nuclei": executable file not found in $PATH

**Comment by tarunKoyalwar** [comment]
@manojdeshmukh45 , this happens because `nuclei` is not installed on your os hence update is failing  .
It looks like you are cloning nuclei repo and using it which is not recommended way of using nuclei. 

we have recently launched our new project [pdtm](https://github.com/projectdiscovery/pdtm) which handles installation and update of all projectdiscovery tools (including nuclei)
