### ISSUE TITLE
The scan slows down as it nears completion

### ISSUE THREAD

**Issue by j4vaovo** [projectdiscovery/nuclei#3721]
nuclei -l all.js -tags token -itags exposures -pt http -stats

<img width="921" alt="搜狗高速浏览器截图20230522010429" src="https://github.com/projectdiscovery/nuclei/assets/128683738/044f4a8f-bf89-4c91-b41a-4e993548176c">

**Comment by nijiinhell** [comment]
yeah i felt that too but i thought it was for network

**Comment by nijiinhell** [comment]
btw your link seems clearly :d

**Comment by MetzinAround** [comment]
It's possible these later templates take a little longer to complete, or it could be a network issues as well.

**Comment by tarunKoyalwar** [comment]
@j4vaovo , as @MetzinAround mentioned it seems the cause is that urls in later templates have high latency . you can confirm that if you run
```
nuclei -l all.js -tags token -itags exposures -pt http -stats -v
``` 
^ it will show you what templates are being run with `-v` verbose mode . and you can just try running that template only to validate if the issue is with that particular domain/url or nuclei. also let us know if you find something in any case. Thanks
