### ISSUE TITLE
Nuclei does not find .yml template files

### ISSUE THREAD

**Issue by 247arjun** [projectdiscovery/nuclei#3743]
When using the `-t` argument to point to template files, Nuclei only finds YAML template files that end in the `.yaml` file extension. It does not seem to recognize the `.yml` file extension.

## Steps to reproduce
1. Create a valid YAML template with the `.yml` file extension.
2. Call Nuclei, pointing to this template file.
3. Observe that no templates are found/loaded.
4. Rename this file to end with the `.yaml` file extension.
5. Call Nuclei, pointing to this template file.
6. Observe that Nuclei loads the template correctly.

**Comment by Mzack9999** [comment]
@247arjun Thanks for opening this issue, it seems like we have some inconsistency in the code base, and `.yml` is handled only via [remote loading](https://github.com/projectdiscovery/nuclei/blob/c182434130b5aab5bcb98a0036a22d57e841edc7/v2/pkg/catalog/loader/remote_loader.go#L70). I'll double check if there is any specific reason why it was excluded for other cases, or fix it otherwise. Ideally in the future the core will rely more on the unmarshaling runtime check, rather than the file extension that could be arbitrary.

**Comment by Mzack9999** [comment]
@247arjun After investigation, it was determined that this is expected behavior as only `.yaml` extensions are considered for templates by design. I'd suggest simply renaming the templates from `.yml` to `.yaml.` Let us know if `.yml` would be necessary for any particular use case or if you have any questions. Thanks!
