### ISSUE TITLE
[issue]

### ISSUE THREAD

**Issue by sickwell** [projectdiscovery/nuclei#398]
**Describe the bug**
workflow not working when you try to run nuclei on mac

#mac:
```
[INF] Using 277 rules (277 templates, 0 workflows)
```
#ubuntu or kali:
```
[INF] Using 299 rules (283 templates, 16 workflows)
```

**Nuclei version**
2.1.1 both platforms,
go 1.15+ both platforms

**Comment by bauthard** [comment]
Hi @sickwell, 

Please have a look at [template-exclusion](https://github.com/projectdiscovery/nuclei#template-exclusion), workflow directory is excluded from default run, so either you need to call the workflow template file instead of directory or update the `.nuclei-ignore` file as per your need.
