### ISSUE TITLE
Broken update-directory flag

### ISSUE THREAD

**Issue by savushkin-yauheni** [projectdiscovery/nuclei#422]
Hi guys!

**Describe the bug**

General usage update-directory is broken:

`nuclei  -update-directory nuclei-templates`

`[FTL] Program exiting: no template/templates provided`

```
if !options.TemplateList {
		// Check if a list of templates was provided and it exists
		if len(options.Templates) == 0 && !options.UpdateTemplates {
			return errors.New("no template/templates provided")
		}

		if options.Targets == "" && !options.Stdin && options.Target == "" && !options.UpdateTemplates {
			return errors.New("no target input provided")
		}
	}
```
that code doesn't allow usage just update-directory flag.
I can bypass it right now by:

`nuclei  -update-directory nuclei-templates -tl a`  
just provide `tl` flag to bypass  `if !options.TemplateList` check.

**Nuclei version**
2.2.0

**Screenshot of the error or bug**
![Screenshot from 2020-11-25 13-19-45](https://user-images.githubusercontent.com/5173352/100214573-1e143880-2f21-11eb-9416-08039d077cf5.png)

Thanks!

**Comment by bauthard** [comment]
Hi @savushkin-yauheni, 

`-update-directory` works along with `-update-templates` not alone, so the expected command would be `nuclei --update-templates -update-directory custom-dir` in case you looking for a custom directory, otherwise, `nuclei -update-templates` is sufficient to install templates on the default location.

**Comment by savushkin-yauheni** [comment]
hm.
What is the right way to use last master version of templates ?
```
git clone https://github.com/projectdiscovery/nuclei-templates.git /root/nuclei-templates/
nuclei --update-templates -update-directory /root/
```
That doesn't work. it overrides directory by 7.2.7 tag release.

**Comment by bauthard** [comment]
@savushkin-yauheni `nuclei -update-template` is the way to use this, `7.2.7` is the latest release created here https://github.com/projectdiscovery/nuclei-templates, that does not include templates added after release, and we don't create new release right away to ensure some time of testing for newly added templates, if you don't want to wait, cloning the templates project is the best way, but you need to choose one method you want to use, mixing both will only create problems and confusions for you.

Closing this as this is not an issue.

**Comment by savushkin-yauheni** [comment]
yes, it is not an issue. But lets clarify ;)

> update-directory works along with -update-templates not alone

so. right now i don't know how to use last master. i tried combine different commands but it doesn't work anyway.
The only way i found:
```
nuclei --update-templates && rm -rf /root/nuclei-templates/
git clone https://github.com/projectdiscovery/nuclei-templates.git /root/nuclei-templates/
```
That works. nuclei would use last master version.

**Comment by bauthard** [comment]
Sure. 

> right now i don't know how to use last master.

Yes, it's intended as said, `-update-templates` download the last release and not the master templates for the known reason as stated in last comment. 

> that does not include templates added after release, and we don't create new release right away to ensure some time of testing for newly added templates.

and we suggest to use released version instead of master, as master may include some templates that produce false positives and we test them before we create new releases that can be downloaded using `-update-templates` flag.

> That works. nuclei would use last master version.

Right, if you always want to use master templates, just do `git clone https://github.com/projectdiscovery/nuclei-templates.git /root/nuclei-templates/`.

Let me know if something is still unclear to you.
