### ISSUE TITLE
Folder "MISC" not taken into consideration

### ISSUE THREAD

**Issue by JoshuaMart** [projectdiscovery/nuclei#430]
Nuclei version : 2.2.0
Nuclei templates : 7.2.9

Hi team,
By performing some tests, it seems that the "misc" folder is not taken into consideration when using `nuclei -t nuclei-templates`.

Likewise it is not possible to use the whole folder with `nuclei -t nuclei-templates/misc/` : 
![](https://zupimages.net/up/20/49/gp0n.png)

Whereas with another folder it works:
![](https://zupimages.net/up/20/49/huxf.png)

With the full path it works :
![](https://zupimages.net/up/20/49/tjaz.png)

I have not checked if other folder are impacted.

Regards,
Jomar

**Comment by Ice3man543** [comment]
@JoshuaMart this is due to the .nuclei-ignore file which disallows execution of the templates under the misc folder without explicitly specifying the individual templates. This is done in order to reduce the amount of noise on default nuclei scans. Check this out - https://github.com/projectdiscovery/nuclei-templates/blob/master/.nuclei-ignore

**Comment by JoshuaMart** [comment]
Hi,
Thank's @Ice3man543 👍 

Have a good day
