### ISSUE TITLE
remove "[INF] Skippedhost from target list"

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/nuclei#4641]
I want to know if there is the possiblity to remove the message errors "[INF] Skippedhost from target list" without removing the functionality of the flag of removing the host from the scan.

I tend to do big scans and this message spams the output and I can't see the results until the scan finishes because the output is polluted with this message.

the only way of removing this message is with `-nmhe` but it also removes the functionality.

This error log should be printed only with `-verbose` or a specific flag, and shouldn't be printed if we only want results

**Comment by dogancanbakir** [comment]
We understand your concern about the `"\[INF\] Skippedhost from target list"` message cluttering your output during large scans. The `-silent` option in Nuclei should help suppress this message. This message is not suppressed by default because some users want to see what got excluded without using the verbose option. However, using the `-silent` option should help in your case.

Feel free to let us know if this helps or if you have any other questions.
