### ISSUE TITLE
SDK Issue

### ISSUE THREAD

**Issue by b0q1** [projectdiscovery/nuclei#4802]
### Nuclei version:
sdk v3.1.10

### Current Behavior:
# github.com\projectdiscovery\nuclei\v3@v3.1.10\pkg\reporting\trackers\gitlab\gitlab.go:109:16: cannot use &customLabels (value of type *"github.com/xanzy/go-gitlab".Labels) as *"github.com/xanzy/go-gitlab".LabelOptions value in struct literal

### Expected Behavior:
build success.

### Steps To Reproduce:
just run sdk examples,see issue like above.

**Comment by b0q1** [comment]
solved.

**Comment by 4blacktea** [comment]
I encountered the same problem in the nuclei 3.1.10 version of the sdk. Could you please share the reasons and solutions? Thank you very much.

**Comment by b0q1** [comment]
> I encountered the same problem in the nuclei 3.1.10 version of the sdk. Could you please share the reasons and solutions? Thank you very much.

Sorry, I've forgotten how I solved it at that time. Maybe reinstall the library or update the golang.

**Comment by 4blacktea** [comment]
I have found the cause of the problem and I am recording it here for future reference for anyone who encounters a similar issue. The reason is a version problem with the dependency github.com/xanzy/go-gitlab. In its v0.95.0 version, there was a change in the parameter "Labels" of the struct "CreateIssueOption". It was changed from "Labels" to "LabelOptions". The default SDK dependency is v0.84.0, but using vendor for automatic dependency management will automatically pull v0.100.0. To resolve this issue, please refrain from enabling vendor or any automatic dependency management feature. I hope this information is helpful.

**Comment by mi-ael** [comment]
single command to fix for lazy people:
`go get -u github.com/xanzy/go-gitlab@v0.84.0`
