### ISSUE TITLE
Error in the proccess of upgrade templates 

### ISSUE THREAD

**Issue by tXambe** [projectdiscovery/nuclei#5472]
### Nuclei version:
Nuclei Engine Version: v3.2.9

### Current Behavior:
Upgrade templates

### Expected Behavior:
Upgrade the templates

### Steps To Reproduce:

1. Run nuclei  -ut 
2. See error...
```

[INF] Your current nuclei-templates v9.9.0 are outdated. Latest is v9.9.2
zsh: killed     nuclei -ut

```

**Comment by dogancanbakir** [comment]
Couldn't repro the issue 
```console
go run . -ut

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.9

                projectdiscovery.io

[INF] Your current nuclei-templates  are outdated. Latest is v9.9.2
[INF] Successfully updated nuclei-templates (v9.9.2) to /Users/dogancanbakir/nuclei-templates. GoodLuck!

Nuclei Templates v9.9.2 Changelog
+-------+-------+---------+
| TOTAL | ADDED | REMOVED |
+-------+-------+---------+
|  9017 |     0 |    9017 |
+-------+-------+---------+
[INF] No new updates found for nuclei templates
```
note: the reason you're seeing 0 added and no previous version is because I mutated the config files in order to repro the issue.

I noticed you're using v3.2.9. Could you retry using the latest version? And, if not working, try removing templates(make sure to backup) + template config (CONFIG_PATH/nuclei/.templates-config.json).

**Comment by dogancanbakir** [comment]
@tXambe was that helpful?
