### ISSUE TITLE
Gitflow and changelog/release

### ISSUE THREAD

**Issue by fguisso** [projectdiscovery/nuclei#658]
I know this is an Open Source project and the fact that you provide this tool for free, I'm grateful.

Today I'm trying to figure out what is the problem with Agent-User random params, I was able to show the problem, but I can't find what's the commit that made this change because you have a lot of fix commits, without commit message.

I think that now when the projects have a lot of contributors e users, you can define a git-flow process, with this you can link PRs and commits on the changelog and release page to help users understand the changes.

For me, I like to help and no just show my problem, but point in the code or maybe make a PR, this way can improve the contribution.

**Comment by ehsandeep** [comment]
@fguisso valid point and something we should follow for making the changes more visible to contributors.

For the issue you raised, I've checked internally and it working as it used to be before, random agent works per template and not per request, to notice the randomization, run test host with multiple templates instead of only one, making it per request make more sense and something we can do it in a future release.

**Comment by Mzack9999** [comment]
Closing as each release provide changelog
