### ISSUE TITLE
Directory style support for the templates

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#71]
This is already supported for now in the following manner. 

```
nuclei -t "path/*.yaml"
```

this issue for an update that allows passing directory name and `nuclei` will look for all the `*.yaml` files in the same directory without breaking the current format, which will be as follows:- 

```
nuclei -t nuclei-templates/cves/ -l targets.txt
```

**Comment by Zeokat** [comment]
I'm a big fan of keep things that works simple and not start offering 1000 ways of do the same thing, because is like run in circles.

Only thinking a little about the new mode, what will happen if i call `-t nuclei-templates/cves` (note that the folder don't ends with slash). You will get `-t nuclei-templates/cves` as a file or as a folder?

This adds extra code complexity and increases the possibility of introducing new bugs with the excuse of introducing a characteristic that already exists. It also extends the guide to learn to use Nuclei.

Don't take it bad, it's just my point of view and i can be wrong also.

**Comment by bauthard** [comment]
Hi @Zeokat, 

I see your point, including new things could cause new issues, but this is something making the project more usable with backword support which is added here https://github.com/projectdiscovery/nuclei/commit/d2e6405ccdff925774253fc66047bed911ccff7e. 

Closing this now.
