### ISSUE TITLE
Implement default config generation for nuclei reporting options

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/nuclei#879]
- [x] Moving [issue-tracker-config.yaml](https://github.com/projectdiscovery/nuclei/blob/master/v2/cmd/nuclei/issue-tracker-config.yaml) to `$HOME/.config/nuclei/report-config.yaml`

**Comment by TheSecEng** [comment]
I think a larger issue is that a `Reporting` client is provided, but it is designed for single use (`cli`). So when you run Nuclei as a server in some custom implementation, duplicates are tracked across multiple executions. This is because the Reporting package implements a dedup storage using leveldb. While this is nice, we provide no way to reset the deduplicate tracking. So we are forced to call `reportingClient.Close()` and then have to reinitialize another instance before our next scan. This is costly and not ideal.

We need to add another function `Clear()` to clear our all previously identified findings.


A better approach would to be first create an interface for the reportingClient and then allow implementations to provide there own reporting client which they can then implement their own dedup logic inside of. Whether that be query a database, using a file based DB or whatever.
