### ISSUE TITLE
[issue] Automatic template update check can trigger Github rate limiting

### ISSUE THREAD

**Issue by CharlieEriksen** [projectdiscovery/nuclei#895]
**Describe the bug**
If you run Nuclei frequently from the same host, you may trigger github to ratelimit you. If you do not have any templates already cached locally, it means that Nuclei will not run. When you get rate limited, you get rate limited for 30 minutes. Meaning that you are stuck for quite a while. 

**Nuclei version**
`2.4.2.`

**Screenshot of the error or bug**
Didn't get a screenshot sadly.

**Comment by rseedorff** [comment]
Hi there,

im hitting the github ratelimit also since we use a docker based setup with a lot of parallel instances running 😕

Just some thoughts on that because i'm already experimenting to solve this issue or find a first quick workaround.

* It would be great if the docker container comes with an already pre-installed 'nuclei-template' (batteries included) to save some bandwidth and prevent hitting the github ratelimit. This could be done by adding a simple `curl` to the latest release artifact and untar them into `/root/nuclei-templates`
* But another problem is that the update check can't be disabled because there is a hardcoded check if the latest update is not older than one hour. In other words the update will be done even if there is already a nearly fresh copy of the latest release https://github.com/projectdiscovery/nuclei/blob/985a7c0f6659fe32b5be3a2e087fa803d86412d9/v2/internal/runner/update.go#L88-L95

**Comment by ehsandeep** [comment]
Hi @rseedorff,

Even template comes pre-installed, we will have the same issue as nuclei will check for updates to ensure it's not running an outdated version of the template release, we are also aware of other cases where the GitHub rate limit is triggered and causing issues, so we are working or cached/s3 storage implementation of templates, where we will poll the GitHub template release from our side and expose static endpoint for users to download templates without any rate limits.

**Comment by rseedorff** [comment]
Hi @ehsandeep,

thx for your quick reply :) I totally agree that there must be more in place to get that approach to work. 

In my opinion i would see an alternative approach to ensure an up to date template within docker... Especially in use case where a lot of containers run in parallel.

The following aspects would help to deal with this issue in the long term:
- Ensure an always up to date docker image (versioned by tags) with the latest templates already included in the docker image. To provide an always updated image your GH Action has to be updated to build a new docker image version, triggered by a new release of the nuclei-template Repo (webhook)...
- Ensure the internal update procedure is more configurable especially regarding the above mentioned hardcoded 1hour check. This could be an cli flag for example `-update-interval 1d|1h|1w`

With this approach you don't need to build a workaround for the GH part, because the initial template setup process is part of the container build already. After pulling an image tag one might to decide to pull an new (updated) version of the docker tag to get the new template updates without hitting GH rate limit. The the internal update routine your already have implemented can also co-exist to this approach, but needs an configurable time interval to.

This would ensure to download the new templates only once (in your build process) and the docker image must be also just pulled once (for each update).

What do you think or did I miss something here?

**Comment by ehsandeep** [comment]
Thank you for suggesting alternatives options but it might not work for the following reason:-

1. We have separate project for templates that has higher frequency for release, per week or it's can be same day as well depending on the situation, so packing templates within nuclei doesn't help as we can not create frequent releases for nuclei project to keep up with templates releases.

2. Having flags to define template update frequency will make the purpose of automatic updates meaningless, as that's the only way we can ensure that new template releases containing fixes for faulty templates getting pushed on the user end.

Overall once we get the new endpoint ready for templates release check, all the issues related to rate limit will be resolved.

**Comment by ehsandeep** [comment]
@CharlieEriksen @rseedorff this is now fixed with the following PR https://github.com/projectdiscovery/nuclei/pull/1026 in the dev version.
