### ISSUE TITLE
robots.txt

### ISSUE THREAD

**Issue by Billybangleballs** [projectdiscovery/nuclei#91]
People are using this in the wild against web servers they have no business with.
There are enough rogue bots clogging up the tubez as it is, at least if it queried robots.txt it could see if it was welcome or not. Just sayin...

**Comment by bauthard** [comment]
Hey @Billybangleballs, 

Nuclei is a template engine that works based on the user-defined path in templates, for example, here is a list of user-curated templates [nuclei-templates](https://github.com/projectdiscovery/nuclei-templates), it's all up to the user how to use it like any other tools, unfortunately this is something not in our control, closing this issue for now.

**Comment by doana** [comment]
Couldn't you build in default support for robots.txt so that people who lack the ability to modify the tool themselves wouldn't be able to scan servers that disalow it? We're seeing a lot of external traffic with your user agent string `Nuclei - Open-source project (github.com/projectdiscovery/nuclei)` in our server logs. Clearly someone is using your tool to scan sites that they don't own for vulnerabilities.

**Comment by geeknik** [comment]
It is possible that https://github.com/temoto/robotstxt or https://github.com/jimsmart/grobotstxt would make this easy to implement.
